install.packages("seqinr")
library(seqinr)
install.packages("stringr") 
library(stringr)  
getwd()
dna_data <- read.fasta(file="insulin.fasta",seqtype ="DNA")
dna_seq <-toupper(paste(dna_data[[1]],collapse=""))
cat ("Insulin DNA sequence:\n", dna_seq, "\n")
a_count <-str_count(dna_seq,"A")
t_count <-str_count(dna_seq,"T")
g_count <-str_count(dna_seq,"G")
c_count <-str_count(dna_seq,"C")
cat ("A:",a_count,"T:", t_count, "G:", g_count, "C:", c_count, "\n")
gc_content <- ((g_count + c_count)/nchar(dna_seq))*100
cat ("GC Content:", gc_content,"%\n")
